:PROPERTIES:
:ID:       9980c345-b9af-4330-a79e-d5811222c993
:END:
#+title: NeRF

* Neural Radiance Fields for Viewing Synthesis
Represents the scene using fully connected layers, where the input is a simple 5D coordinate (spatial location $x,y,z$, viewing direction $\theta,\phi$) and output is volume density and view dependent emitted radiance at that spacial location. Only input required to optimize is the set of images with known camera pose.
** Introduction
- Synthesizing novel views of complex scenes.
- Optimizing a single perceptron to represent 5d coordinate ($x, y, z, \theta, \phi$) to a single volume density and view dependent RGB color.
- #TODO [[id:de23e439-bb45-4427-90f6-3c99c3e14006][NeRF for three cameras of three views]]
- Overcomes storage space requirements with /discretized/ voxel grids ([[id:69860a13-1206-4b0f-9a75-78533cdde787][discretized voxel grids]])

** Technical Contributions
- Approach for representing continuous scenes with complex geometries as 5D neural radiance fields, using _basic_ MLPs
- Differentiable rendering procedure.
- Positional encoding technique
** Related works
- Mapping 3d spacial location to an implicit representation of the shape (signed distance of the location) is already being done. But they are unable to reproduce complex realistic scenes
*** Neural 3D shape representation
- 3D shapes to signed distances or occupancy fields
- requires GT 3D geometries from synthetic 3D shapes
- Neural shape representations can also be optimized with 2D images in subsequent works
- Sitzmann et al use a 3d representation by simply outputting a feature vector and RGB color at each continuous 3D coordinate
- These techniques are promizing but result in oversmooth rendering
*** View synthesis and image-based rendering
- From a dense sample of views, photorealistic novel views can be generated by simple light field sample interpolation techniques
- Mesh based representation of a scene with either diffuse or view dependent appearance
- Differentiable rasterizers or pathtracers: image --> Mesh representation
- A template mesh is first initialized and then modified - unavailable for unconstrainted real-world scenes
*** Volumetric representations for photorealistic view synthesis
- Less visually distracting artefacts
- Use of large datasets
- Limited by poor time and space complexity due to their discrete sampling

They circumvent this problem by encoding /continuous volume/ within the parameters of a fully connected NN. Higher quality and requires fraction of storage of those sampled volume representations
** Neural radiance field
- Represent continuous scene
- Input: $\mathbf{x} = (x, y, z)$, $(\theta, \phi)$
- Output: $\mathbf{c} = (r, g, b)$ and volume density $\sigma$
- 3-D direction as unit vector $d$
- Therefore: $F_{\Theta}: (\mathbf{x}, \mathbf{d}) \rightarrow (\mathbf{c}, \sigma)$ and optimize weights $\Theta$
- The network predicts the volume density $\sigma$ as a function of only $\mathbf{x}$
- RGB color $\mathbf{c}$ is predicted using both inputs $(\mathbf{x}, \mathbf{d})$
- $\mathbf{x}$ with 8 fully connected layers $\rightarrow$ outputs $\sigma$ and 256-features
- The 256 features with $\mathbf{d}$ passed to 1 FC and outputs $\mathbf{c}$
** Volume rendering with Radiance Fields
- Color rendering is done using classical techniques #TODO what is it?
- To get color they use [[id:68453cdb-c1fc-4b6b-9cff-fb2fa9b1baaa][stratified sampling]] with $[t_{n}, t_{f}]$ which enables them to represent continuous scene representation
** Optimizing Neural Radiance Field
Two improvements:
*** Positional encoding
- Deep networks are biased towards learning lower frequency functions
- *Mapping inputs to higher dimentional space enables better fitting of data that contain high frequency variations*
- Therefore: $F_{\Theta} = F'_{\Theta} \circ \gamma$
- $\gamma$ is mapping from $\mathbb{R}$ to $\mathbb{R}^{2L}$
- $\gamma(\dot)$ is applied separately to each values in $\mathbf{x}$ which is normalized between $[-1, 1]$
- $L = 10$ for $\gamma(\mathbf{x})$ and $L = 4$ for $\gamma(\mathbf{d})$
*** Hierarchical sampling procedure
- Samples are proportionally rendered based on the expected effect on the final rendering
- Two networks are used: coarse $N_{c}$ and fine $N_{f}$
- The color of the ray is rendered using both the networks
**** Implementation
- Batch size: $4096$ rays
- $N_{c} = 64$
- $N_{f} = 128$
- Adam optimizer LR: $5 \times 10^{-4}$ decay exponentially to $5 \times 10^{-5}$, $\beta_{1} = 0.9$, $\beta_{2} = 0.999$, $\epsilon = 10^{-7}$
- optimization takes $100$ to $300$k iterations
